SELECT
    RH.LN_NO,
    RH.NCCA_KEY, 
    RH.REV_NO,
    TT.ACC_CD,
    TT.WRK_LOC_CD,
    TT.POS_CD,
    CAST(RH.LAST_UPD_DT AS DATE) AS LAST_UPD_DT_,
    RH.LAST_UPD_TM,
    RH.LAST_UPD_NM,
    RH.COVG_REV_STAT_CD,
    HI.FLD_NM,
    HI.OLD_VALUE,
    HI.NEW_VALUE,
    TT.MISC1_TXT,
    TXT.NARR_TXT
FROM 
    NCMV.COVG_REV_HIST RH

JOIN 
    (SELECT 
        T.NCCA_KEY, 
        T.ACC_CD, 
        T.WRK_LOC_CD, 
        T.POS_CD, 
        T.MISC1_TXT
     FROM 
        NCMV.DEF T
     WHERE 
        T.MISC1_TXT IN ('1', '2', '3', '4') OR T.MISC1_TXT LIKE '%CQ%') AS TT
    ON TT.NCCA_KEY = RH.NCCA_KEY

JOIN 
    NCMV.DEF_HIST HI
    ON RH.NCCA_KEY = HI.NCCA_KEY

JOIN 
    NCMV.DISC_TXT TXT
    ON HI.NCCA_KEY = TXT.NC_KEY
    AND RH.LAST_UPD_DT = TXT.LAST_UPD_DT
    AND RH.LAST_UPD_TM = TXT.LAST_UPD_TM

WHERE 
    RH.AP_DESC NOT LIKE '%YP%'
    AND RH.LAST_UPD_DT >= '2024-01-01';
