SELECT 
    O.LINE_NO, 
    Q.REL_WRK_PKG_ID,
    O.PLAN_TITLE,
    O.ORDER_ID,
    Q.NCCA_KEY,
    O.ACC_CD,
    O.ACC_POS_CD,
    O.WORK_LOC_CD,
    DES.FEAT_DESC,
    DES.DESC_DESC,
    CAST(O.MFG_SCH_CMPL_DT AS DATE) AS INSERT_DATE,
    ST.MISC1_TXT,
    ST.COORD_1_ID, 
    ST.COORD_2_ID, 
    ST.COORD_3_ID

FROM 
    OWI_STG_INQ_VW.OWI_ORDER_LATEST_REV O

JOIN 
    NCMV.OWI_ORD Q
    ON Q.ORD_ID = O.ORDER_ID

LEFT JOIN 
    NCMV.NC_VISIBILITY N
    ON Q.NCCA_KEY = N.NC_KEY

LEFT JOIN 
    NCMV.FEAT_DEF_DESC_FULL DES
    ON DES.FEAT_CD = N.FND_FEAT_CD
    AND DES.DESC_CD = N.FND_DESC_CD

LEFT JOIN 
    (SELECT 
        NCCA_KEY, 
        MISC1_TXT, 
        COORD_1_ID, 
        COORD_2_ID, 
        COORD_3_ID
     FROM 
        NCMV.DEF) ST
    ON ST.NCCA_KEY = Q.NCCA_KEY

WHERE 
    O.ORDER_ID LIKE '%CRO%'
    AND O.ORDER_ID NOT LIKE '%RRMV%'
    AND O.MFG_SCH_CMPL_DT >= '2024-01-01'
    AND O.PGM_ID = '737'
    AND O.CVN_ID NOT LIKE '%YP%'
    AND O.LINE_NO = '8984'

GROUP BY 
    O.LINE_NO, 
    Q.REL_WRK_PKG_ID, 
    O.PLAN_TITLE, 
    O.ORDER_ID, 
    Q.NCCA_KEY, 
    O.ACC_CD, 
    O.ACC_POS_CD, 
    O.WORK_LOC_CD, 
    DES.FEAT_DESC, 
    DES.DESC_DESC, 
    O.MFG_SCH_CMPL_DT, 
    ST.MISC1_TXT, 
    ST.COORD_1_ID, 
    ST.COORD_2_ID, 
    ST.COORD_3_ID;
