SELECT DISTINCT
    O.NC_KEY,
    V.ORD_ID, 
    O.LN_NO,
    O.FNDACCPOS,
    O.JOB_ID,
    ORD.PLAN_TITLE, 
    ORD.INSERT_DATE,
    FF.FEAT_DESC,
    FF.DESC_DESC
FROM 
    NCMV.NC_VISIBILITY O

JOIN 
    NCMV.OWI_ORD V
    ON O.NC_KEY = V.NCCA_KEY

JOIN 
    (SELECT 
         ORDER_ID,
         PLAN_TITLE,
         INSERT_DATE
     FROM 
         OWI_INT_INQ_VW.OWI_ORDER_LATEST_REV
     WHERE 
         PGM_ID = '737'
         AND INSERT_DATE BETWEEN '2024-01-01 00:00:00.000000' AND '2024-08-28 23:59:00.000000'
         AND ORDER_ID NOT LIKE '%RRMV%'
         AND CVN_ID NOT LIKE '%YP%') AS ORD
    ON ORD.ORDER_ID = V.ORD_ID

LEFT JOIN 
    OWI_INT_INQ_VW.BIQFD_CC_DETAIL CC
    ON CC.NCR_ID = O.NC_KEY

LEFT JOIN 
    NCMV.FEAT_DEF_DESC_FULL FF
    ON O.FND_DESC_CD = FF.DESC_CD 
    AND O.FND_FEAT_CD = FF.FEAT_CD;
