SELECT DISTINCT
    B.LINE_NO, 
    B.ORDER_ID, 
    B.PLAN_TITLE, 
    O.ACCEPT_ACTION_TXT, 
    CAST(O.ETL_LAST_UPDT_TS AS DATE) AS TIME_STAMP,
    MAX(O.ETL_LAST_UPDT_TS) OVER (PARTITION BY B.ORDER_ID) AS LATEST_TIMESTAMP,
    DES.FEAT_DESC,
    DES.DESC_DESC

FROM 
    owi_int_inq_vw.owi_order_latest_rev B

JOIN 
    OWI_STG_INQ_VW.ORDER_STEP_ACCEPT_AA_TXT O
    ON B.ORDER_KEY = O.ORDER_KEY

JOIN 
    ncmv.owi_ord Q
    ON Q.ORD_ID = B.ORDER_ID

JOIN 
    NCMV.NC_VISIBILITY N
    ON Q.NCCA_KEY = N.NC_KEY

JOIN 
    ncmv.feat_def_desc_full DES
    ON DES.FEAT_CD = N.FND_FEAT_CD
    AND DES.DESC_CD = N.FND_DESC_CD

WHERE 
    B.PGM_ID = '737'
    AND B.CVN_ID NOT LIKE '%YP%'
    AND B.ORDER_ID LIKE '%CRO%'
    AND O.ACCEPT_ACTION_TXT LIKE '%REDLINE%'
    AND O.ETL_LAST_UPDT_TS >= '2023-12-31 00:00:00.000000'

GROUP BY 
    B.LINE_NO, 
    B.ORDER_ID, 
    B.PLAN_TITLE, 
    O.ACCEPT_ACTION_TXT, 
    CAST(O.ETL_LAST_UPDT_TS AS DATE), 
    DES.FEAT_DESC, 
    DES.DESC_DESC;
