WITH QQ AS (
    SELECT NCCA_KEY, REL_WRK_PKG_ID
    FROM NCMV.OWI_ORD
    WHERE REL_WRK_PKG_ID = 'IP-00RQS0842Y'
),
ORD AS (
    SELECT ORDER_KEY, CVN_ID, ORDER_ID, PGM_ID, LINE_NO, PLAN_TITLE, PROD_STATUS_CD
    FROM OWI_INT_INQ_VW.OWI_ORDER_LATEST_REV
    WHERE PGM_ID = '737'
    AND ORDER_ID LIKE '%CRO%'
    AND ORDER_ID NOT LIKE '%RRMV%'
    AND CVN_ID NOT LIKE '%YP%'
),
TS AS (
    SELECT SUM_LAST_UPDT_TS, ORDER_KEY
    FROM OWI_INT_INQ_VW.ORDER_STEP_SUM_TXT_RPT
    WHERE SUM_LAST_UPDT_TS >= '2024-01-01 00:00:00.000000'
),
TT AS (
    SELECT MISC1_TXT, NCCA_KEY
    FROM NCMV.DEF
    WHERE MISC1_TXT LIKE '%CQ%' OR MISC1_TXT IN ('1', '2', '3', '4')
),
FEAT AS (
    SELECT D.NCCA_KEY, FF.FEAT_DESC, FF.DESC_DESC
    FROM NCMV.DEF D
    JOIN NCMV.FEAT_DEF_DESC_FULL FF
        ON D.FND_DESC_CD = FF.DESC_CD
        AND D.FND_FEAT_CD = FF.FEAT_CD
),
DT AS (
    SELECT NC_KEY, NARR_TXT
    FROM NCMV.LATEST_DISC_TXT_DISC_TXT
    WHERE NARR_TXT LIKE '%RTS%' OR NARR_TXT LIKE '%RETURN TO SHOP%' 
          OR NARR_TXT LIKE '%RTS,%' OR NARR_TXT LIKE '%RTS.%'
          OR NARR_TXT LIKE '% RTS%' OR NARR_TXT LIKE '%RTS %'
)
SELECT
    ORD.PGM_ID,
    TT.MISC1_TXT,
    ORD.LINE_NO,
    ORD.CVN_ID,
    Q.NCCA_KEY,
    Q.REL_WRK_PKG_ID,
    ORD.ORDER_ID,
    ORD.PLAN_TITLE,
    DT.NARR_TXT,
    FEAT.FEAT_DESC,
    FEAT.DESC_DESC,
    ORD.PROD_STATUS_CD,
    CAST(TS.SUM_LAST_UPDT_TS AS DATE)
FROM NCMV.OWI_ORD Q
JOIN QQ ON QQ.NCCA_KEY = Q.NCCA_KEY
LEFT JOIN ORD ON Q.ORD_ID = ORD.ORDER_ID
JOIN TS ON TS.ORDER_KEY = ORD.ORDER_KEY
JOIN TT ON Q.NCCA_KEY = TT.NCCA_KEY
JOIN FEAT ON TT.NCCA_KEY = FEAT.NCCA_KEY
JOIN DT ON Q.NCCA_KEY = DT.NC_KEY
WHERE ORD.PROD_STATUS_CD = 'RTS';
